apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: ecommerce-prod
  labels:
    app: service-discovery
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        environment: production
    spec:
      containers:
        - name: service-discovery
          image: alejocastro/service-discovery-ecommerce-boot:prod-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 40
            periodSeconds: 40
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: ecommerce-prod
  labels:
    app: service-discovery
    environment: production
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
    - name: http
      port: 8761
      targetPort: 8761
