apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce-stage
  labels:
    app: cloud-config
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
        environment: staging
    spec:
      containers:
        - name: cloud-config
          image: selimhorri/cloud-config-ecommerce-boot:stage-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9296
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 20
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 40
            periodSeconds: 40
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ecommerce-stage
  labels:
    app: cloud-config
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: cloud-config
  ports:
    - name: http
      port: 9296
      targetPort: 9296
