apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce-stage
  labels:
    app: order-service
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        environment: staging
    spec:
      containers:
        - name: order-service
          image: alejocastro/order-service-ecommerce-boot:stage-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8300
          envFrom:
            - configMapRef:
                name: microservices-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8300
            initialDelaySeconds: 20
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8300
            initialDelaySeconds: 40
            periodSeconds: 30
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce-stage
  labels:
    app: order-service
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: 8300
      targetPort: 8300
