apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce-stage
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: alejocastro/order-service-ecommerce-boot:stage-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8300
          envFrom:
            - configMapRef:
                name: microservices-config
          readinessProbe:
            httpGet:
              path: /order-service/actuator/health
              port: 8300
            initialDelaySeconds: 150
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /order-service/actuator/health
              port: 8300
            initialDelaySeconds: 180
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce-stage
  labels:
    app: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - name: http
      port: 8300
      targetPort: 8300
