apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce-stage
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: alejocastro/product-service-ecommerce-boot:stage-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8500
          envFrom:
            - configMapRef:
                name: microservices-config
          readinessProbe:
            httpGet:
              path: /product-service/actuator/health
              port: 8500
            initialDelaySeconds: 150
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /product-service/actuator/health
              port: 8500
            initialDelaySeconds: 180
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: ecommerce-stage
  labels:
    app: product-service
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - name: http
      port: 8500
      targetPort: 8500