apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce-dev
  labels:
    app: cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
        - name: cloud-config
          image: alejocastro/cloud-config-ecommerce-boot:dev-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9296
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ecommerce-dev
  labels:
    app: cloud-config
spec:
  type: ClusterIP
  selector:
    app: cloud-config
  ports:
    - name: http
      port: 9296
      targetPort: 9296
