apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce-dev
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: alejocastro/payment-service-ecommerce-boot:dev-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8400
          envFrom:
            - configMapRef:
                name: microservices-config
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8400
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8400
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce-dev
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8400
      targetPort: 8400
