apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: ecommerce-dev
  labels:
    app: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: alejocastro/service-discovery-ecommerce-boot:dev-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: ecommerce-dev
  labels:
    app: service-discovery
spec:
  type: ClusterIP
  selector:
    app: service-discovery
  ports:
    - name: http
      port: 8761
      targetPort: 8761
